# Generated by Django 3.0.6 on 2020-05-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('film_id', models.AutoField(primary_key=True, serialize=False)),
                ('film_name_rus', models.CharField(max_length=200)),
                ('film_name_orig', models.CharField(default=' ', max_length=200)),
                ('film_year', models.IntegerField()),
                ('film_poster', models.ImageField(default='none/no-img.jpg', upload_to='filmpic/')),
                ('film_kp_url', models.CharField(max_length=200)),
                ('film_genres', models.ManyToManyField(to='restpost.Genre')),
            ],
        ),
    ]
