# Generated by Django 3.0.6 on 2020-05-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='film_desc',
            field=models.TextField(default=' '),
        ),
    ]
