# Generated by Django 3.0.6 on 2020-05-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restpost', '0002_film_film_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='film_desc',
            field=models.TextField(default='_'),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_name_orig',
            field=models.CharField(default='_', max_length=200),
        ),
    ]
