# Generated by Django 3.0.6 on 2020-05-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restpost', '0003_auto_20200512_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='film_name_rus',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
