# Generated by Django 3.0.6 on 2020-05-13 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restpost', '0004_auto_20200512_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name_rus', models.CharField(max_length=32)),
                ('country_name_int', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_name_short', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('currency_name_long', models.CharField(max_length=32)),
                ('currency_today_course', models.FloatField()),
                ('currency_course_day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name_rus', models.CharField(max_length=100)),
                ('location_name_orig', models.CharField(max_length=100)),
                ('location_latitude', models.FloatField()),
                ('location_longitude', models.FloatField()),
                ('location_opening_time', models.TimeField()),
                ('location_close_time', models.TimeField()),
                ('location_visit_cost', models.FloatField()),
                ('location_visit_duration', models.IntegerField()),
                ('location_picture', models.ImageField(default='none/no-img.jpg', upload_to='locationpic/')),
                ('fk_country_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_locations', to='restpost.Country')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='currency_of_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='restpost.Currency'),
        ),
    ]
