# Generated by Django 3.0.6 on 2020-05-13 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restpost', '0005_auto_20200513_0809'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('location_latitude', 'location_longitude')},
        ),
    ]
