# Generated by Django 3.0.6 on 2020-05-13 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restpost', '0006_auto_20200513_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='fk_country_location',
        ),
        migrations.CreateModel(
            name='FilmLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_picture', models.ImageField(default='none/no-img.jpg', upload_to='filmlocframes/')),
                ('film_scene_desc', models.CharField(max_length=200)),
                ('fk_film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmed_in', to='restpost.Film')),
                ('fk_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmed_here', to='restpost.Location')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='films_were_here',
            field=models.ManyToManyField(through='restpost.FilmLocation', to='restpost.Film'),
        ),
    ]
