# Generated by Django 3.0.6 on 2020-05-13 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restpost', '0007_auto_20200513_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmlocation',
            name='fk_film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wasfilmedin', to='restpost.Film'),
        ),
        migrations.AlterField(
            model_name='filmlocation',
            name='fk_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herelilmed', to='restpost.Location'),
        ),
    ]
