# Generated by Django 3.0.6 on 2020-05-13 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restpost', '0008_auto_20200513_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='films_were_here',
        ),
        migrations.AddField(
            model_name='location',
            name='fk_country_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='country_locations', to='restpost.Country'),
        ),
        migrations.DeleteModel(
            name='FilmLocation',
        ),
    ]
