# Generated by Django 3.0.6 on 2020-05-13 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restpost', '0009_auto_20200513_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_reason', models.CharField(max_length=64)),
                ('fk_film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restpost.Film')),
                ('fk_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restpost.Location')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='films_were_here',
            field=models.ManyToManyField(through='restpost.FilmLocation', to='restpost.Film'),
        ),
    ]
