# Generated by Django 3.0.6 on 2020-05-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restpost', '0010_auto_20200513_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmlocation',
            name='invite_reason',
        ),
        migrations.AddField(
            model_name='filmlocation',
            name='film_frame',
            field=models.ImageField(default='none/no-img.jpg', upload_to='filmframeloc/'),
        ),
        migrations.AddField(
            model_name='filmlocation',
            name='film_scene_desc',
            field=models.CharField(default='эта сцена', max_length=200),
        ),
    ]
