# Generated by Django 3.0.6 on 2020-05-13 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restpost', '0011_auto_20200513_1327'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filmlocation',
            unique_together={('fk_location', 'fk_film')},
        ),
    ]
